// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uassmtjyebmrezxzddcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhc3NtdGp5ZWJtcmV6eHpkZGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDc2OTEsImV4cCI6MjA2OTYyMzY5MX0.qB543sl8tmwTKByp52pSnE9MFWq05DHtdgVEcHYC3Ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});